# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Humble - pre-release

on:
  workflow_dispatch:
    inputs:
      dependency_level:
        description: 'The depth of the depends-on tree to be included in the overlay workspace (-1 implies unlimited, default: 0)'
        required: false
        default: 0
        type: number
  pull_request:
    branches:
      - humble
    types:
      - opened # default
      - reopened # default
      - synchronize # default
      - labeled # also if a label changes

env:
  ROS_DISTRO: humble

jobs:
  default:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@reusable_prerelease
    with:
      ros_distro: humble
      dependency_level: ${{ inputs.dependency_level }}
