# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Jazzy - pre-release

on:
  workflow_dispatch:
    inputs:
      downstream_depth:
        description: 'The depth of the depends-on tree to be included in the overlay workspace (-1 implies unlimited, default: 0)'
        required: false
        default: 0
        type: number
  pull_request:
    branches:
      - jazzy
    types:
      - opened # default
      - reopened # default
      - synchronize # default
      - labeled # also if a label changes

env:
  ROS_DISTRO: jazzy

jobs:
  default:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-prerelease.yml@reusable_prerelease
    with:
      ros_distro: jazzy
      # downstream_depth is not set on pull_request event
      prerelease_downstream_depth: ${{ inputs.downstream_depth || 0}}
