# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Rolling - pre-release

on:
  workflow_dispatch:
    inputs:
      dependency_level:
        description: 'The depth of the depends-on tree to be included in the overlay workspace (-1 implies unlimited, default: 0)'
        required: false
        default: 0
        type: number
  pull_request:
    branches:
      - master
    types:
      - labeled
  issue_comment:
    # This event will only trigger a workflow run if the workflow file exists on the default branch.
    # we have to check if the comment is a) from a PR and b) if it is targeting correct branch
    types:
      - created

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: printenv
      - run: |
          set -xe
          echo ${{github.event_name}}
          echo ${{github.event.issue.pull_request}}
          pr_url="${{ github.event.issue.pull_request.url }}"
          if [ -n "$pr_url" ]; then
            pr_json=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$pr_url")
            head_branch=$(echo "$pr_json" | grep -oP '"head":\s*{[^}]*"ref":\s*"\K[^"]+')
            echo "PR head branch: $head_branch"
          else
            echo "No PR URL found in issue."
          fi
          echo ${{(contains(github.event.comment.body, '/check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))}}
  nameme:
    if: |
      (github.event_name == 'issue_comment' && github.event.pull_request && github.event.pull_request.head.ref == 'master' && (contains(github.event.comment.body, '/check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))) ||
      (github.event_name == 'pull_request' && (contains(github.event.label.name, 'check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))) ||
      (github.event_name == 'workflow_dispatch')

    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted, rolling]

    name: name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: industrial_ci
        env:
          PRERELEASE: true
          # hardcode to 1 if check-prerelease-downstream is triggered, otherwise use input
          PRERELEASE_DOWNSTREAM_DEPTH: ${{ ((github.event_name == 'issue_comment' && contains(github.event.comment.body, '/check-prerelease-downstream')) ||  (github.event_name == 'pull_request' && contains(github.event.label.name, 'check-prerelease-downstream'))) && 1 || inputs.dependency_level}}
          BASEDIR: ${{ github.workspace }}/.work
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          DOCKER_IMAGE: ghcr.io/ros-controls/ros:${{ matrix.ROS_DISTRO }}-ubuntu-testing
        uses: ros-industrial/industrial_ci@master
