name: Rolling debian Binary Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  rolling_debian_binary:
    name: Rolling debian build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: rolling
    container: ghcr.io/christophfroehlich/ros:rolling-debian
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_control
      - run: |
          source /opt/ros2_ws/install/setup.bash
          vcs import src < https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_control.${{ env.ROS_DISTRO }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon build --packages-skip rqt_controller_manager
          colcon test --packages-skip rqt_controller_manager
