# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Rolling - pre-release

on:
  workflow_dispatch:
    inputs:
      downstream_depth:
        description: 'The depth of the depends-on tree to be included in the overlay workspace (-1 implies unlimited, default: 0)'
        required: false
        default: -1
        type: number
  pull_request:
    branches:
      - master
    types:
      - opened # default
      - reopened # default
      - synchronize # default
      - labeled # also if a label changes


jobs:
  get_prerelease_depth:
    runs-on: ubuntu-latest
    outputs:
      PRERELEASE_DEPTH: ${{ steps.set_depth.outputs.PRERELEASE_DEPTH }}
    steps:
      - name: Set prerelease depth
        # Use 0 for pull_request, otherwise the provided input.
        # The with: field is very restrictive, so we need this job
        id: set_depth
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PRERELEASE_DEPTH=0'" >> $GITHUB_OUTPUT
          else
            echo "PRERELEASE_DEPTH='${{ github.event.inputs.downstream_depth }}'" >> $GITHUB_OUTPUT
          fi
  default:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted, rolling]
    needs: get_prerelease_depth

    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-prerelease.yml@reusable_prerelease
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      prerelease_downstream_depth: 0
