# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Rolling - pre-release

on:
  workflow_dispatch:
    inputs:
      dependency_level:
        description: 'The depth of the depends-on tree to be included in the overlay workspace (-1 implies unlimited, default: 0)'
        required: false
        default: 0
        type: number
  pull_request:
    branches:
      - master
    types:
      - labeled
  pull_request_review_comment:
    # we have to check if the PR is targeting the correct branch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: printenv
      - run: |
          set -xe
          echo ${{github.event_name}}
          echo ${{github.event.pull_request.head.ref}}
          echo ${{github.event.pull_request.head.label}}
          echo ${{(contains(github.event.comment.body, '/check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))}}
  default:
    if: |
      (github.event_name == 'pull_request_review_comment' && github.event.pull_request.head.ref == 'master' && (contains(github.event.comment.body, '/check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))) ||
      (github.event_name == 'pull_request' && (contains(github.event.label.name, 'check-prerelease') || contains(github.event.label.name, 'check-prerelease-downstream'))) ||
      (github.event_name == 'workflow_dispatch')

    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted, rolling]

    name: ${{ github.env.ROS_DISTRO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: industrial_ci
        env:
          PRERELEASE: true
          # hardcode to 1 if check-prerelease-downstream is triggered, otherwise use input
          PRERELEASE_DOWNSTREAM_DEPTH: ${{ ((github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/check-prerelease-downstream')) ||  (github.event_name == 'pull_request' && contains(github.event.label.name, 'check-prerelease-downstream'))) && 1 || inputs.dependency_level}}
          BASEDIR: ${{ github.workspace }}/.work
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          DOCKER_IMAGE: ghcr.io/ros-controls/ros:${{ matrix.ROS_DISTRO }}-ubuntu-testing
        uses: ros-industrial/industrial_ci@master
